### ISSUE TITLE
Does this have 4.1?

### ISSUE THREAD

**Issue by brimur** [ErezHorev/dockerized_nfs_server#4]
Hi, this is more of a question than an issue. My current NAS supports NFS v4 but not 4.1 Mutipathing so I was thinking about creating a nfs server in docker to take over the NFS service. Does this one have v4.1 with Multipathing? Thanks

**Comment by brimur** [comment]
Just an FYI, I attempted the above but when I try to start the service I get an error. "Not starting NFS kernel daemon: no support in current kernel". Probably not possible.

**Comment by ErezHorev** [comment]
Hi @brimur ,
Your question is most welcome.
This project actually wraps the ubuntu (xenial) nfs-kernel-version
You can read about it at [https://launchpad.net/ubuntu/xenial/+package/nfs-kernel-server](url).
They do say it supports NFSv4 but didn't see anything about 4.1. you'll might have to crawl it online.

In regard to your error: "Not starting NFS kernel daemon: no support in current kernel", it seems that your host's kernel doesn't support nfs. please see reference on doc: [https://github.com/ErezHorev/dockerized_nfs_server#make-sure-native-host-kernel-support-nfs](url)

Thank you

**Comment by brimur** [comment]
Thanks for your response. Very helpful
