### ISSUE TITLE
Starting nfs server within a container generates [nfsd] kernel threads

### ISSUE THREAD

**Issue by stcarrez** [ErezHorev/dockerized_nfs_server#7]
Thanks for the nfs server trick it was really helpful!

If you start the nfs server from a container, and then stop your container, this will leave your host
with several [nfsd] kernel threads. After starting and stopping a container that provides nfs server
I've observed serveral [nfsd] kernel threads lying arround on the host system. You cannot stop them
and I've got arround 450 of these kernel threads.

I've tried to run the command:

`service nfs-kernel-start stop
`

before stopping the container but there is still the [nfsd] kernel thread leak (8 for each run).

Any idea on how to fix that?

**Comment by ErezHorev** [comment]
@stcarrez thank you for raising this issue and i'm glad this project is helpful ;)
Interesting issue... 
I'm going to investigate it
Please be patient as it may take a couple of days
Thank you

**Comment by ErezHorev** [comment]
@stcarrez please provide the following:
- Operating System (+version)
- Docker version

**Comment by ErezHorev** [comment]
I can't reproduce it on centos 7.1.1503, don't see any nfsd kernel threads there.
I guess you're using ubuntu

**Comment by stcarrez** [comment]
Yes, this is ubuntu 16.04.3 LTS with:

linux-image-4.4.0-97-generic
nfs-kernel-server  1:1.2.8-9ubuntu12.1
nfs-common 1:1.2.8-9ubuntu12.1
docker.io 1.12.6-0ubuntu1~16.04.1

**Comment by ErezHorev** [comment]
got it , thanks

**Comment by ErezHorev** [comment]
I managed to reproduce it. thanks.
This is obviously related to the fact that the nfs server we use is not in the userspace but in kernel space. 
There's not much about it on the web (leaking nfs kernel server inside docker containers) and i lack  the knowledge around kernels (that didn't stop me from investigating it, hoping for a chance to learn new things).

I apologize but won't be able to fix it soon. 
As i wrote on README, this project is not recommended for production and my SLA here is poor anyhow. 

I originally started the nfs service inside the container without testing/realizing all consequences. 
The only fix i can think of is to pull the nfs service start/stop out of the docker container and relocate it in the stop/start wrapping scripts. 
this will leave out the nfsd communication with the kernel out of the container.
I wouldn't use this project in practice unless its only for testing.
This project mainly manipulates exports inside the docker container and nothing more.
think you can fork this project or just copy/paste bits of it to a simple bash/python script that does pretty much the same -> start nfs, set exports, stop nfs.

Thank you
